"""initial production schema

Revision ID: a2e86758a930
Revises: 
Create Date: 2026-09-21 00:35:37.782317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e86758a930'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('opponent_name', sa.String(length=100), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('our_score', sa.Integer(), nullable=False),
    sa.Column('opponent_score', sa.Integer(), nullable=False),
    sa.Column('our_formation', sa.String(length=20), nullable=False),
    sa.Column('opponent_formation', sa.String(length=20), nullable=True),
    sa.Column('tactical_problem', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('coach_observations', sa.Text(), nullable=True),
    sa.Column('scenario_payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_team_name'), ['team_name'], unique=False)

    op.create_table('teams',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('default_formation', sa.String(length=20), nullable=True),
    sa.Column('tactical_identity', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_team_name'), ['team_name'], unique=True)

    op.create_table('decisions',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scenario_profile', sa.String(length=32), nullable=False),
    sa.Column('leading_option_id', sa.String(length=50), nullable=False),
    sa.Column('generated_from', sa.String(length=32), nullable=False),
    sa.Column('decision_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('coach_selections',
    sa.Column('selection_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option_id', sa.String(length=50), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('selection_id')
    )
    with op.batch_alter_table('coach_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_selections_decision_id'), ['decision_id'], unique=True)

    op.create_table('decision_outcomes',
    sa.Column('outcome_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('final_our_score', sa.Integer(), nullable=False),
    sa.Column('final_opponent_score', sa.Integer(), nullable=False),
    sa.Column('coach_assessment', sa.String(length=20), nullable=False),
    sa.Column('outcome_summary', sa.Text(), nullable=False),
    sa.Column('observed_effects', sa.JSON(), nullable=False),
    sa.Column('next_time_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    with op.batch_alter_table('decision_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_outcomes_decision_id'), ['decision_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_outcomes_decision_id'))

    op.drop_table('decision_outcomes')
    with op.batch_alter_table('coach_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_selections_decision_id'))

    op.drop_table('coach_selections')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_scenario_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_team_name'))

    op.drop_table('teams')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_team_name'))

    op.drop_table('scenarios')
    # ### end Alembic commands ###
