"""add pilot interest capture

Revision ID: bc48155e770c
Revises: a2e86758a930
Create Date: 2026-09-21 19:17:26.241973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc48155e770c'
down_revision: Union[str, Sequence[str], None] = 'a2e86758a930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_interests',
    sa.Column('pilot_interest_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coach_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('club_or_team', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('would_use_in_real_matches', sa.String(length=10), nullable=False),
    sa.Column('join_private_pilot', sa.String(length=10), nullable=False),
    sa.Column('willingness_to_pay_monthly_gbp', sa.Integer(), nullable=True),
    sa.Column('most_valuable_feature', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pilot_interest_id')
    )
    with op.batch_alter_table('pilot_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pilot_interests_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pilot_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pilot_interests_email'))

    op.drop_table('pilot_interests')
    # ### end Alembic commands ###
