"""add ai analysis observability

Revision ID: eeb475d40692
Revises: bc48155e770c
Create Date: 2026-09-22 22:31:37.172316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb475d40692'
down_revision: Union[str, Sequence[str], None] = 'bc48155e770c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_runs',
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=40), nullable=True),
    sa.Column('revised', sa.Boolean(), nullable=False),
    sa.Column('review_attempt_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('analysis_run_id')
    )
    with op.batch_alter_table('ai_analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_runs_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_runs_team_name'), ['team_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_runs_team_name'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_runs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_runs_model_name'))

    op.drop_table('ai_analysis_runs')
    # ### end Alembic commands ###
